DEFAULTS = {
    'server.uri'              : 'ldap://127.0.0.1:12345',
    'server.user'             : 'cn=Manager,dc=my-domain,dc=com',
    'server.password'         : 'secret',
    'server.escape_queries'   : False,
    'server.start_tls'        : False,

    'cache.cache'             : False,
    'cache.memcached'         : '127.0.0.1:11211',
    'cache.timeout'           : 300,

    'users.baseDN'            : 'ou=users,dc=my-domain,dc=com',
    'users.attrmap'           : {"rdn": "uid", 
                                 "id": "uid", 
                                 "login": "uid",
                                 "fullname": "cn", 
                                 "email": "mail",
                                 'location': 'l'},
    'users.scope'             : '1',
    'users.queryFilter'       : '(objectClass=inetOrgPerson)',
    'users.objectClasses'     : '["inetOrgPerson"]',
    'users.memberOfSupport'   : False,

    'groups.baseDN'           : 'ou=groups,dc=my-domain,dc=com',
    'groups.attrmap'          : {"rdn": "cn", 
                                 "id": "cn", 
                                 "title": "o",
                                 "description": "description"},
    'groups.scope'            : '1',
    'groups.queryFilter'      : '(objectClass=groupOfNames)',
    'groups.objectClasses'    : '["groupOfNames"]',
    'groups.memberOfSupport'  : False,
}