name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    uses: "./.github/workflows/qa.yaml"

  tests:
    uses: "./.github/workflows/tests.yaml"
