name: Test the pas.plugins.ldap code
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
        plone:
          - "6.0.0a3"

    steps:
      - uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install -y slapd ldap-utils

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Install package
        run: |
          make VENV=off install

      - name: Run tests
        run: |
          make VENV=off test-ignore-warnings
